esphome:
  name: slimmelezer
  platform: ESP8266
  board: d1_mini

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "SlimmeLezer Fallback Hotspot"
    password: "slimmelezer"

captive_portal:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

logger:
  #level: verbose
  baud_rate: 0

uart:
  baud_rate: 115200 
  rx_pin: D7

dsmr:
  update_interval: 1s

sensor:
  - platform: dsmr
    energy_delivered_tariff1:
      name: dsmr_energy_delivered_tariff1
    energy_delivered_tariff2:
      name: dsmr_energy_delivered_tariff2
    energy_returned_tariff1:
      name: dsmr_energy_returned_tariff1
    energy_returned_tariff2:
      name: dsmr_energy_returned_tariff2
    power_delivered:
      name: power_delivered
      unit_of_measurement: 'Wh'
      accuracy_decimals: 0
      filters:
        - multiply: 1000
    power_returned:
      name: power_returned
      unit_of_measurement: 'Wh'
      accuracy_decimals: 0
      filters:
        - multiply: 1000
    voltage_l1:
      name: voltage_l1
    voltage_l2:
      name: voltage_l2
    voltage_l3:
      name: voltage_l3
    current_l1:
      name: current_l1
    current_l2:
      name: current_l2
    current_l3:
      name: current_l3
    gas_delivered:
      name: gas_delivered
    gas_delivered_be:
      name: gas_delivered_be

text_sensor:
  - platform: dsmr
    identification:
      name: 'dsmr_identification'
    p1_version:
      name: 'dsmr_p1_version'
    p1_version_be:
      name: 'dsmr_p1_version_be'